Cerambyxtasy\Oltree\MainBundle\Entity\Hexagon:
    type: entity
    table: hexagon
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields: 
      name:
          type: string
          length: 255
          nullable: true          
      extended_id:
          type: string
          length: 255          
    oneToOne:
      journal_entry:
        targetEntity: JournalEntry
        inversedBy: hexagon       
    manyToOne:
      map:
        targetEntity: Map
        inversedBy: hexagons
        