<?php

namespace Proxies\__CG__\Cerambyxtasy\Oltree\MainBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Satrap extends \Cerambyxtasy\Oltree\MainBundle\Entity\Satrap implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDetails($details)
    {
        $this->__load();
        return parent::setDetails($details);
    }

    public function getDetails()
    {
        $this->__load();
        return parent::getDetails();
    }

    public function setJsonConfiguration($jsonConfiguration)
    {
        $this->__load();
        return parent::setJsonConfiguration($jsonConfiguration);
    }

    public function getJsonConfiguration()
    {
        $this->__load();
        return parent::getJsonConfiguration();
    }

    public function setUser(\Cerambyxtasy\Oltree\MainBundle\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function addJournal(\Cerambyxtasy\Oltree\MainBundle\Entity\Journal $journals)
    {
        $this->__load();
        return parent::addJournal($journals);
    }

    public function removeJournal(\Cerambyxtasy\Oltree\MainBundle\Entity\Journal $journals)
    {
        $this->__load();
        return parent::removeJournal($journals);
    }

    public function getJournals()
    {
        $this->__load();
        return parent::getJournals();
    }

    public function setPatroller(\Cerambyxtasy\Oltree\MainBundle\Entity\User $patroller = NULL)
    {
        $this->__load();
        return parent::setPatroller($patroller);
    }

    public function getPatroller()
    {
        $this->__load();
        return parent::getPatroller();
    }

    public function setMap(\Cerambyxtasy\Oltree\MainBundle\Entity\Map $map = NULL)
    {
        $this->__load();
        return parent::setMap($map);
    }

    public function getMap()
    {
        $this->__load();
        return parent::getMap();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'details', 'json_configuration', 'map', 'journals', 'patroller');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}